//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReportesWH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class siixsem_users_t
    {
        public int se_id_user { get; set; }
        public string se_name { get; set; }
        public string se_pass { get; set; }
        public int se_id_rol { get; set; }
    }
}
